---
- name: Install Java 1.8 and some basic dependencies
  become: yes
  become_method: sudo 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.7.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Download JBoss from jboss.org
  become: yes
  become_method: sudo  
  get_url:
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  become: yes
  become_method: sudo  
  unarchive:
    dest: /usr/share
    src: /opt/jboss-as-7.1.1.Final.zip
    creates: /usr/share/jboss-as
    copy: no

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  become: yes
  become_method: sudo  
  command: /bin/mv jboss-as-7.1.1.Final jboss-as 
  args:
    chdir: /usr/share 
    creates: /usr/share/jboss-as

- name: Copying standalone.xml configuration file
  become: yes
  become_method: sudo
  template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  become: yes
  become_method: sudo  
  group:
    name: jboss

- name: Add user "jboss"
  become: yes
  become_method: sudo  
  user:
    name: jboss
    group: jboss
    home: /usr/share/jboss-as

- name: Change ownership of JBoss installation
  become: yes
  become_method: sudo
  file:
    path: /usr/share/jboss-as/
    owner: jboss
    group: jboss
    state: directory
    recurse: yes

- name: Copy the init script
  become: yes
  become_method: sudo  
  copy:
    src: jboss-as-standalone.sh
    dest: /etc/init.d/jboss
    mode: 0755

- name: copy the jboss modules
  become: yes
  become_method: sudo
  get_url:
    url: https://repo1.maven.org/maven2/org/jboss/modules/jboss-modules/1.1.5.GA/jboss-modules-1.1.5.GA.jar
    dest: /usr/share/jboss-as/jboss-modules.jar

- name: Workaround for systemd bug
  become: yes
  become_method: sudo  
  shell: service jboss start && chkconfig jboss on
  ignore_errors: yes

- name: Enable JBoss to be started at boot
  become: yes
  become_method: sudo
  service:
    name: jboss
    enabled: yes
    state: started
